ACTIONS = [
    {"name": "站立", "motion_id": 111, "risk": "low", "desc": "RECOVERYSTAND"},
    {"name": "趴下", "motion_id": 101, "risk": "low", "desc": "GETDOWN"},
    {"name": "坐下", "motion_id": 143, "risk": "medium", "desc": "sit"},
    {"name": "作揖", "motion_id": 123, "risk": "medium", "desc": "bow"},
    {"name": "握左手", "motion_id": 141, "risk": "medium", "desc": "shake left hand"},
    {"name": "握右手", "motion_id": 142, "risk": "medium", "desc": "shake right hand"},
    {"name": "扭屁股", "motion_id": 144, "risk": "medium", "desc": "hip circle"},
    {"name": "伸懒腰", "motion_id": 146, "risk": "medium", "desc": "stretch"},
    {"name": "头画圈", "motion_id": 145, "risk": "medium", "desc": "head circle"},
    {"name": "坐下左摆头", "motion_id": 148, "risk": "medium", "desc": "sit head left"},
    {"name": "坐下右摆头", "motion_id": 149, "risk": "medium", "desc": "sit head right"},
    {"name": "坐下左右摆头", "motion_id": 150, "risk": "medium", "desc": "sit head left-right"},
    {"name": "跳上台阶", "motion_id": 126, "risk": "high", "desc": "jump up step"},
    {"name": "跳下台阶", "motion_id": 137, "risk": "high", "desc": "jump down step"},
    {"name": "跳下高台", "motion_id": 147, "risk": "very_high", "desc": "jump down platform"},
    {"name": "抱手跳跃", "motion_id": 500, "risk": "very_high", "desc": "jump with raised hands"},
    {"name": "后空翻", "motion_id": 121, "risk": "very_high", "desc": "back flip"},
    {"name": "前空翻", "motion_id": 122, "risk": "very_high", "desc": "front flip"},
    {"name": "右侧空翻", "motion_id": 127, "risk": "very_high", "desc": "right flip"},
    {"name": "左侧空翻", "motion_id": 128, "risk": "very_high", "desc": "left flip"},
]
